runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: templates/css
- url: /images
  static_dir: templates/images

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
